async function fetchChunkedBase64(paths){const parts=await Promise.all(paths.map(async path=>{const r=await fetch(resolveAsset(path),{cache:'no-store'});if(!r.ok)throw new Error(`Asset unavailable: ${path}`);return (await r.text()).trim();}));return parts.join('');}
async function loadPreparedIndex(){if(!manifest.searchIndex)return false;try{const r=await fetch(resolveAsset(manifest.searchIndex),{cache:'no-store'});if(!r.ok)throw new Error('Prepared search index unavailable');const data=await r.json(),pages=Array.isArray(data.pages)?data.pages:[];for(let i=0;i<sheets.length;i++){const p=pages.find(x=>Number(x.page)===i+1)||pages[i]||{};pageTexts[i]=p.text||'';pageWords[i]=Array.isArray(p.words)?p.words:[];indexedPages=i+1;}preparedIndex=true;indexReady=true;setStatus(`Prepared searchable text ready — ${sheets.length} sheets`);return true;}catch(e){console.error(e);return false;}}
async function startIndex(){if(indexReady||indexing)return;indexing=true;if(await loadPreparedIndex()){indexing=false;if($('search').value.trim())renderSearch();return;}try{if(!window.pdfjsLib||!manifest.sourcePdf)throw new Error('Native PDF text unavailable');pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';const doc=await pdfjsLib.getDocument({url:resolveAsset(manifest.sourcePdf),disableAutoFetch:false}).promise;const total=Math.min(sheets.length,doc.numPages);for(let i=1;i<=total;i++){const p=await doc.getPage(i),viewport=p.getViewport({scale:1}),content=await p.getTextContent(),items=[];for(const item of content.items){if(!item.str||!item.str.trim())continue;const tx=pdfjsLib.Util.transform(viewport.transform,item.transform),fontHeight=Math.max(2,Math.hypot(tx[2],tx[3])),x=tx[4],y=tx[5]-fontHeight,w=Math.max(2,item.width||fontHeight);items.push({text:item.str,x:x/viewport.width,y:y/viewport.height,w:w/viewport.width,h:fontHeight/viewport.height,source:'native'});}pageWords[i-1]=items;pageTexts[i-1]=items.map(x=>x.text).join(' ');indexedPages=i;if($('search').value.trim())renderSearch();await new Promise(r=>setTimeout(r,0));}indexReady=true;indexing=false;setStatus(`Searchable native text ready — ${indexedPages} sheets`);if($('search').value.trim())renderSearch();renderHighlights();}catch(e){indexing=false;setStatus('Native text index unavailable. Image OCR will be used when searching.');console.error(e);}}
function ocrDbName(){return `ab-plan-ocr-${projectId}-${manifest.packageVersion||manifest.setDate||'1'}`.replace(/[^a-z0-9_-]/gi,'-');}
function openOcrDb(){return new Promise((resolve,reject)=>{const req=indexedDB.open(ocrDbName(),1);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains('pages'))db.createObjectStore('pages');};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
async function getCachedOcr(i){try{const db=await openOcrDb(),value=await new Promise((resolve,reject)=>{const tx=db.transaction('pages','readonly'),req=tx.objectStore('pages').get(`p${i+1}`);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});db.close();return value||null;}catch{return null;}}
async function saveCachedOcr(i,data){try{const db=await openOcrDb();await new Promise((resolve,reject)=>{const tx=db.transaction('pages','readwrite');tx.objectStore('pages').put(data,`p${i+1}`);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});db.close();}catch{}}
async function hydrateOcrCache(){if(preparedIndex)return;for(let i=0;i<sheets.length;i++){const c=await getCachedOcr(i);if(c&&Array.isArray(c.words)){const native=pageWords[i]||[];pageWords[i]=[...native,...c.words];pageTexts[i]=`${pageTexts[i]||''} ${c.text||''}`.trim();ocrDone.add(i);}}if($('search').value.trim())renderSearch();}
async function ensureOcrWorker(){if(ocrWorker)return ocrWorker;if(!window.Tesseract)throw new Error('OCR library unavailable');ocrWorker=await Tesseract.createWorker('eng',1,{logger:m=>{if(m.status==='recognizing text'&&$('search').value.trim())setStatus(`OCR sheet ${Math.min(ocrDone.size+1,sheets.length)}/${sheets.length} — ${Math.round((m.progress||0)*100)}%`);}});return ocrWorker;}
function parseTsv(tsv,w,h){const words=[];for(const line of String(tsv||'').split(/\r?\n/).slice(1)){const c=line.split('\t');if(c.length<12||c[0]!=='5')continue;const text=(c.slice(11).join('\t')||'').trim(),conf=Number(c[10]);if(!text||conf<25)continue;const x=Number(c[6]),y=Number(c[7]),ww=Number(c[8]),hh=Number(c[9]);if(ww<=0||hh<=0)continue;words.push({text,x:x/w,y:y/h,w:ww/w,h:hh/h,source:'ocr',confidence:conf/100});}return words;}
async function loadSheetImage(i){let im=imageCache.get(i+1);if(!im){im=new Image();im.decoding='async';const s=sheets[i];if(Array.isArray(s.chunks)&&s.chunks.length){const b64=await fetchChunkedBase64(s.chunks);im.src=`data:${s.mime||'image/png'};base64,${b64}`;}else{im.src=resolveAsset(sheetImage(s))+`?v=${encodeURIComponent(manifest.packageVersion||manifest.setDate||1)}`;}imageCache.set(i+1,im);}if(!(im.complete&&im.naturalWidth))await im.decode();return im;}
async function ocrPage(i){if(preparedIndex||ocrDone.has(i))return;const cached=await getCachedOcr(i);if(cached&&Array.isArray(cached.words)){pageWords[i]=[...(pageWords[i]||[]),...cached.words];pageTexts[i]=`${pageTexts[i]||''} ${cached.text||''}`.trim();ocrDone.add(i);return;}const im=await loadSheetImage(i),maxWidth=2400,ratio=Math.min(1,maxWidth/im.naturalWidth),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(im.naturalWidth*ratio));canvas.height=Math.max(1,Math.round(im.naturalHeight*ratio));canvas.getContext('2d',{alpha:false}).drawImage(im,0,0,canvas.width,canvas.height);const worker=await ensureOcrWorker(),result=await worker.recognize(canvas,{}, {tsv:true}),words=parseTsv(result.data.tsv,canvas.width,canvas.height),text=(result.data.text||words.map(x=>x.text).join(' ')).replace(/\s+/g,' ').trim();pageWords[i]=[...(pageWords[i]||[]),...words];pageTexts[i]=`${pageTexts[i]||''} ${text}`.trim();ocrDone.add(i);await saveCachedOcr(i,{text,words});}
async function startOcrScan(){if(preparedIndex||manifest.allowBrowserOcr===false||ocrScanning||ocrDone.size===sheets.length||ocrFailed)return;ocrScanning=true;try{const order=[page-1,...Array.from({length:sheets.length},(_,i)=>i)].filter((v,i,a)=>a.indexOf(v)===i);for(const i of order){await ocrPage(i);if($('search').value.trim())renderSearch();await new Promise(r=>setTimeout(r,20));}ocrScanning=false;if($('search').value.trim())renderSearch();}catch(e){ocrScanning=false;ocrFailed=true;setStatus('Image OCR could not finish; indexed PDF text remains available.');console.error(e);}}
