'use strict';
if('serviceWorker' in navigator){navigator.serviceWorker.getRegistrations().then(rs=>rs.forEach(r=>r.unregister())).catch(()=>{});}
const $=id=>document.getElementById(id),app=$('app'),scroll=$('scroll'),stage=$('stage'),plan=$('plan'),highlightLayer=$('highlights');
const params=new URLSearchParams(location.search);const isMobile=params.get('mobile')==='1'||matchMedia('(max-width:760px)').matches||/iPhone|iPad|iPod|Android/i.test(navigator.userAgent);
let registry=[],projectEntry=null,manifest=null,manifestUrl=null,sheets=[],projectId=params.get('project')||'',page=1,rotation=0,scale=1,mode='page',naturalW=2400,naturalH=1600,loadToken=0,dragging=false,sx=0,sy=0,sl=0,st=0,toastTimer,activeSearch='';
let pageTexts=[],pageWords=[],indexReady=false,indexing=false,indexedPages=0,preparedIndex=false,ocrDone=new Set(),ocrScanning=false,ocrWorker=null,ocrFailed=false;const imageCache=new Map();
let touchMode='',touchStartX=0,touchStartY=0,touchScrollLeft=0,touchScrollTop=0,pinchStartDistance=0,pinchStartScale=1,pinchContentX=0,pinchContentY=0,touchMoved=false,lastTap=0;
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function norm(s){return String(s??'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();}
function termsFor(q){return [...new Set(norm(q).split(' ').filter(Boolean))];}
function resolveAsset(path){return new URL(path,manifestUrl).href;}
function sheetNumber(s){return s.number??s.n??'';}function sheetTitle(s){return s.title??s.t??'';}function sheetGroup(s){return s.discipline??s.group??s.g??'Plans';}function sheetImage(s){return s.image??s.file??s.f??'';}
function setStatus(text){$('searchStatus').textContent=text;}
function toast(msg){clearTimeout(toastTimer);$('toast').textContent=msg;$('toast').style.display='block';toastTimer=setTimeout(()=>$('toast').style.display='none',2600);}
function closeSidebar(){$('sidebar').classList.remove('open');$('shade').classList.remove('open');}
function openSidebar(){$('sidebar').classList.add('open');$('shade').classList.add('open');setTimeout(()=>$('search').focus(),100);startIndex();}
function showLoading(text){$('loadingText').textContent=text;$('loading').style.display='grid';$('error').style.display='none';$('statusDot').classList.remove('ready');$('status').textContent='Loading sheet';}
function showError(text){$('loading').style.display='none';$('errorText').textContent=text;$('error').style.display='grid';$('statusDot').classList.remove('ready');$('status').textContent='Load error';}
function ready(){$('loading').style.display='none';$('error').style.display='none';$('statusDot').classList.add('ready');$('status').textContent='Sheet ready';}
function currentSheet(){return sheets[page-1]||{};}
function renderProjectSelect(){const sel=$('projectSelect');sel.innerHTML=registry.map(p=>`<option value="${esc(p.id)}"${p.id===projectId?' selected':''}>${esc(p.name)}</option>`).join('');sel.onchange=()=>location.href=`viewer.html?project=${encodeURIComponent(sel.value)}${isMobile?'&mobile=1':''}`;}
function renderSheets(){const q=$('search').value.trim();if(q){renderSearch();return;}const list=$('sheetList');list.innerHTML='';let last='';sheets.forEach((s,i)=>{const group=sheetGroup(s);if(group!==last){const h=document.createElement('div');h.className='group';h.textContent=group;list.appendChild(h);last=group;}const b=document.createElement('button');b.className='sheet'+(i+1===page?' active':'');b.innerHTML=`<span class="num">${esc(sheetNumber(s))}</span><span class="sheetName">${esc(sheetNumber(s))} - ${esc(sheetTitle(s))}</span>`;b.onclick=()=>{activeSearch='';go(i+1);};list.appendChild(b);});$('count').textContent=`${sheets.length} sheet${sheets.length===1?'':'s'}`;list.querySelector('.active')?.scrollIntoView({block:'nearest'});}
function pageSearchText(i){const s=sheets[i]||{};return norm(`${sheetNumber(s)} ${sheetTitle(s)} ${sheetGroup(s)} ${pageTexts[i]||''}`);}
function pageMatches(i,terms){const text=pageSearchText(i);return terms.length>0&&terms.every(t=>text.includes(t));}
function pageHitCount(i,terms){let hits=0;for(const w of pageWords[i]||[]){const t=norm(w.text);for(const term of terms)if(t.includes(term))hits++;}return hits||1;}
function makeSnippet(i,terms){const raw=String(pageTexts[i]||'').replace(/\s+/g,' ').trim();if(!raw)return 'Matching sheet title or indexed drawing text.';const lower=raw.toLowerCase();let pos=-1,found='';for(const t of terms){const p=lower.indexOf(t);if(p>=0&&(pos<0||p<pos)){pos=p;found=t;}}if(pos<0)return 'Matching drawing text found on this sheet.';const start=Math.max(0,pos-70),end=Math.min(raw.length,pos+found.length+120);return `${start?'…':''}${raw.slice(start,end).trim()}${end<raw.length?'…':''}`;}
function renderSearch(){const q=$('search').value.trim();activeSearch=q;$('clear').style.display=q?'block':'none';if(!q){setStatus(indexReady?`Searchable text ready — ${sheets.length} sheets`:'Preparing searchable text…');renderSheets();renderHighlights();return;}const terms=termsFor(q);startIndex();if(!preparedIndex&&terms.length&&q.length>=2)startOcrScan();const results=[];for(let i=0;i<sheets.length;i++)if(pageMatches(i,terms))results.push({i,hits:pageHitCount(i,terms),snippet:makeSnippet(i,terms)});const list=$('sheetList');list.innerHTML='';if(!results.length){const progress=!indexReady||ocrScanning?`Searching plans… indexed ${indexedPages}/${sheets.length}${ocrScanning?`, OCR ${ocrDone.size}/${sheets.length}`:''}`:'No plan sheets contain that text.';list.innerHTML=`<div class="empty">${esc(progress)}</div>`;}else results.forEach(r=>{const s=sheets[r.i],b=document.createElement('button');b.className='result'+(r.i+1===page?' active':'');b.innerHTML=`<span class="num">${esc(sheetNumber(s))}</span><span><span class="resultTitle">${esc(sheetNumber(s))} - ${esc(sheetTitle(s))}</span><span class="resultMeta">${r.hits} highlighted instance${r.hits===1?'':'s'}</span><span class="resultSnippet">${esc(r.snippet)}</span></span>`;b.onclick=()=>{activeSearch=q;go(r.i+1);};list.appendChild(b);});const suffix=preparedIndex?' · prepared index':ocrScanning?` · OCR ${ocrDone.size}/${sheets.length}`:ocrFailed?' · native text only':ocrDone.size===sheets.length?' · native text + OCR':'';setStatus(`${results.length} matching sheet${results.length===1?'':'s'}${suffix}`);renderHighlights();}
function addHit(r){if(!Number.isFinite(r.x)||!Number.isFinite(r.y)||!Number.isFinite(r.w)||!Number.isFinite(r.h))return;const d=document.createElement('div');d.className='hit';d.style.left=`${Math.max(0,r.x)*100}%`;d.style.top=`${Math.max(0,r.y)*100}%`;d.style.width=`${Math.max(.001,r.w)*100}%`;d.style.height=`${Math.max(.002,r.h)*100}%`;highlightLayer.appendChild(d);}
function renderHighlights(){highlightLayer.innerHTML='';const q=activeSearch||$('search').value.trim();if(!q)return;const terms=termsFor(q),i=page-1;for(const w of pageWords[i]||[]){const t=norm(w.text);if(terms.some(term=>t.includes(term)))addHit(w);}const count=highlightLayer.childElementCount;if(count){$('currentMeta').textContent=`${manifest.setName||'Plan Set'} · ${count} orange highlight${count===1?'':'s'}`;$('mobileMeta').textContent=`Sheet ${page} of ${sheets.length} · ${count} highlight${count===1?'':'s'}`;}}
