function rotatedSize(){return rotation%180?{w:naturalH,h:naturalW}:{w:naturalW,h:naturalH};}
function transformImage(){const W=naturalW*scale,H=naturalH*scale;stage.style.width=(rotation%180?H:W)+'px';stage.style.height=(rotation%180?W:H)+'px';plan.style.width=highlightLayer.style.width=W+'px';plan.style.height=highlightLayer.style.height=H+'px';let tr='translate(0,0) rotate(0deg)';if(rotation===90)tr=`translate(${H}px,0) rotate(90deg)`;else if(rotation===180)tr=`translate(${W}px,${H}px) rotate(180deg)`;else if(rotation===270)tr=`translate(0,${W}px) rotate(270deg)`;plan.style.transform=highlightLayer.style.transform=tr;$('zoomLabel').textContent=mode==='page'?'Page':mode==='width'?'Width':Math.round(scale*100)+'%';$('mFit').textContent=mode==='page'?'Fit':Math.round(scale*100)+'%';}
function fit(which=mode){mode=which;const s=rotatedSize(),pad=isMobile?12:56,aw=Math.max(220,scroll.clientWidth-pad),ah=Math.max(220,scroll.clientHeight-pad);scale=which==='width'?aw/s.w:Math.min(aw/s.w,ah/s.h);scale=Math.max(.06,Math.min(scale,5));transformImage();requestAnimationFrame(()=>{scroll.scrollLeft=Math.max(0,(stage.offsetWidth-scroll.clientWidth)/2);scroll.scrollTop=0;});}
function zoomAt(mult,clientX,clientY){mode='custom';const rect=scroll.getBoundingClientRect(),px=(clientX??rect.left+rect.width/2)-rect.left,py=(clientY??rect.top+rect.height/2)-rect.top,old=scale,contentX=(scroll.scrollLeft+px)/old,contentY=(scroll.scrollTop+py)/old;scale=Math.max(.06,Math.min(5,scale*mult));transformImage();scroll.scrollLeft=contentX*scale-px;scroll.scrollTop=contentY*scale-py;}
function setRotation(value){rotation=((Number(value)%360)+360)%360;if(![0,90,180,270].includes(rotation))rotation=0;localStorage.setItem(`ab-plan-rotation-${projectId}-${isMobile?'mobile':'desktop'}`,String(rotation));$('orientation').value=String(rotation);fit(mode==='custom'?'page':mode);updateHeader();}
function updateHeader(){const s=currentSheet(),title=`${sheetNumber(s)} - ${sheetTitle(s)}`,meta=`${manifest.setName||'Plan Set'} · Sheet ${page} of ${sheets.length}`;$('currentTitle').textContent=$('mobileTitle').textContent=title;$('currentMeta').textContent=meta;$('mobileMeta').textContent=`Sheet ${page} of ${sheets.length}`;$('pageInput').value=page;$('pageInput').max=sheets.length;$('pageTotal').textContent=`/ ${sheets.length}`;$('mPage').textContent=`${page} / ${sheets.length}`;['prev','mPrev','floatPrev'].forEach(id=>$(id).disabled=page===1);['next','mNext','floatNext'].forEach(id=>$(id).disabled=page===sheets.length);$('orientation').value=String(rotation);document.title=`${title} | AB Plan Viewer`;const hash=new URLSearchParams(location.hash.slice(1));hash.set('page',page);history.replaceState(null,'',`${location.pathname}${location.search}#${hash.toString()}`);renderSheets();renderHighlights();}
async function showPage(){const token=++loadToken,s=currentSheet();showLoading(`Loading ${sheetNumber(s)} - ${sheetTitle(s)}…`);updateHeader();try{const im=await loadSheetImage(page-1);if(token!==loadToken)return;naturalW=im.naturalWidth;naturalH=im.naturalHeight;plan.src=im.src;plan.alt=`${sheetNumber(s)} - ${sheetTitle(s)}`;fit(mode==='custom'?'page':mode);ready();renderHighlights();[page-1,page+1].filter(p=>p>=1&&p<=sheets.length).forEach(p=>loadSheetImage(p-1).catch(()=>{}));if(activeSearch&&!preparedIndex&&!ocrDone.has(page-1))ocrPage(page-1).then(()=>{renderSearch();renderHighlights();}).catch(()=>{});}catch(e){imageCache.delete(page);showError(`Unable to load ${sheetNumber(s)} - ${sheetTitle(s)}. Refresh and try again.`);}}
function go(p){page=Math.max(1,Math.min(sheets.length,Number(p)||1));closeSidebar();showPage();}
async function loadProject(){showLoading('Loading project…');try{const registryResponse=await fetch('projects.json?v=2',{cache:'no-store'});if(!registryResponse.ok)throw new Error('Project registry could not be loaded');const data=await registryResponse.json();registry=Array.isArray(data.projects)?data.projects:[];if(!registry.length)throw new Error('No projects are available');projectEntry=registry.find(p=>p.id===projectId)||registry[0];projectId=projectEntry.id;manifestUrl=new URL(projectEntry.manifest,location.href);const manifestResponse=await fetch(manifestUrl.href,{cache:'no-store'});if(!manifestResponse.ok)throw new Error('Project package manifest could not be loaded');manifest=await manifestResponse.json();sheets=Array.isArray(manifest.sheets)?manifest.sheets:[];if(!sheets.length)throw new Error('This project package has no sheets');pageTexts=new Array(sheets.length).fill('');pageWords=Array.from({length:sheets.length},()=>[]);const hashPage=Number(new URLSearchParams(location.hash.slice(1)).get('page'))||1;page=Math.max(1,Math.min(sheets.length,hashPage));const stored=localStorage.getItem(`ab-plan-rotation-${projectId}-${isMobile?'mobile':'desktop'}`);rotation=stored!==null?Number(stored):(isMobile?(manifest.mobileDefaultRotation??0):(manifest.defaultRotation??0));if(![0,90,180,270].includes(rotation))rotation=0;$('projectLabel').textContent=`${manifest.projectName||projectEntry.name} · ${manifest.setName||'Plan Set'}`;$('download').href=manifest.sourcePdf?resolveAsset(manifest.sourcePdf):'#';$('download').download=`${manifest.projectName||projectEntry.name} - ${manifest.setName||'Plans'}.pdf`;renderProjectSelect();renderSheets();$('count').textContent=`${sheets.length} sheets`;await loadPreparedIndex();hydrateOcrCache();showPage();if(!preparedIndex)setTimeout(startIndex,800);}catch(e){showError(e.message||'Unable to load this project.');console.error(e);}}
$('search').oninput=renderSearch;$('search').onfocus=startIndex;$('clear').onclick=()=>{$('search').value='';$('clear').style.display='none';activeSearch='';renderSheets();renderHighlights();$('search').focus();};$('prev').onclick=$('mPrev').onclick=$('floatPrev').onclick=()=>go(page-1);$('next').onclick=$('mNext').onclick=$('floatNext').onclick=()=>go(page+1);$('pageInput').onchange=e=>go(e.target.value);$('pageInput').onkeydown=e=>{if(e.key==='Enter'){go(e.target.value);e.target.blur();}};$('zoomIn').onclick=$('mPlus').onclick=()=>zoomAt(1.2);$('zoomOut').onclick=$('mMinus').onclick=()=>zoomAt(1/1.2);$('fitWidth').onclick=()=>fit('width');$('fitPage').onclick=$('mFit').onclick=()=>fit('page');$('rotateLeft').onclick=()=>setRotation(rotation-90);$('rotateRight').onclick=$('mRotate').onclick=()=>setRotation(rotation+90);$('orientation').onchange=e=>setRotation(e.target.value);$('retry').onclick=showPage;$('full').onclick=()=>document.fullscreenElement?document.exitFullscreen():$('viewer').requestFullscreen().catch(()=>{});$('share').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);toast('Share link copied.');}catch{prompt('Copy this link:',location.href);}};$('mobileMenu').onclick=$('mPage').onclick=openSidebar;$('shade').onclick=closeSidebar;$('mobileHide').onclick=()=>app.classList.add('hiddenBars');$('viewer').onclick=e=>{if(app.classList.contains('hiddenBars')&&e.target.closest('.scroll'))app.classList.remove('hiddenBars');};
scroll.addEventListener('mousedown',e=>{if(e.button!==0)return;dragging=true;sx=e.clientX;sy=e.clientY;sl=scroll.scrollLeft;st=scroll.scrollTop;scroll.classList.add('dragging');e.preventDefault();});window.addEventListener('mousemove',e=>{if(!dragging)return;scroll.scrollLeft=sl-(e.clientX-sx);scroll.scrollTop=st-(e.clientY-sy);});window.addEventListener('mouseup',()=>{dragging=false;scroll.classList.remove('dragging');});
function distance(a,b){return Math.hypot(b.clientX-a.clientX,b.clientY-a.clientY);}function midpoint(a,b){const r=scroll.getBoundingClientRect();return{x:(a.clientX+b.clientX)/2-r.left,y:(a.clientY+b.clientY)/2-r.top};}
scroll.addEventListener('touchstart',e=>{if(e.touches.length===1){const t=e.touches[0];touchMode='pan';touchStartX=t.clientX;touchStartY=t.clientY;touchScrollLeft=scroll.scrollLeft;touchScrollTop=scroll.scrollTop;touchMoved=false;}else if(e.touches.length>=2){const a=e.touches[0],b=e.touches[1],m=midpoint(a,b);touchMode='pinch';pinchStartDistance=Math.max(1,distance(a,b));pinchStartScale=scale;pinchContentX=(scroll.scrollLeft+m.x)/scale;pinchContentY=(scroll.scrollTop+m.y)/scale;mode='custom';touchMoved=true;}e.preventDefault();},{passive:false});
scroll.addEventListener('touchmove',e=>{if(touchMode==='pan'&&e.touches.length===1){const t=e.touches[0],dx=t.clientX-touchStartX,dy=t.clientY-touchStartY;if(Math.abs(dx)>2||Math.abs(dy)>2)touchMoved=true;scroll.scrollLeft=touchScrollLeft-dx;scroll.scrollTop=touchScrollTop-dy;}else if(e.touches.length>=2){const a=e.touches[0],b=e.touches[1],m=midpoint(a,b);if(touchMode!=='pinch'){touchMode='pinch';pinchStartDistance=Math.max(1,distance(a,b));pinchStartScale=scale;pinchContentX=(scroll.scrollLeft+m.x)/scale;pinchContentY=(scroll.scrollTop+m.y)/scale;}scale=Math.max(.06,Math.min(5,pinchStartScale*(distance(a,b)/pinchStartDistance)));transformImage();scroll.scrollLeft=pinchContentX*scale-m.x;scroll.scrollTop=pinchContentY*scale-m.y;touchMoved=true;}e.preventDefault();},{passive:false});
scroll.addEventListener('touchend',e=>{if(e.touches.length===1){const t=e.touches[0];touchMode='pan';touchStartX=t.clientX;touchStartY=t.clientY;touchScrollLeft=scroll.scrollLeft;touchScrollTop=scroll.scrollTop;}else if(e.touches.length===0){const now=Date.now();if(!touchMoved&&now-lastTap<280){mode==='page'?zoomAt(1.8):fit('page');lastTap=0;}else if(!touchMoved)lastTap=now;touchMode='';}e.preventDefault();},{passive:false});
// Prevent browser zoom while this viewer is open. Ctrl/Cmd + wheel controls only the plan canvas.
document.addEventListener('wheel',e=>{if(!(e.ctrlKey||e.metaKey))return;e.preventDefault();zoomAt(e.deltaY<0?1.12:1/1.12,e.clientX,e.clientY);},{capture:true,passive:false});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&['+','=','-','0'].includes(e.key)){e.preventDefault();if(e.key==='0')fit('page');else zoomAt(e.key==='-'?1/1.2:1.2);return;}const tag=document.activeElement?.tagName;if(['INPUT','SELECT','TEXTAREA'].includes(tag))return;if(e.key==='ArrowLeft'||e.key==='PageUp')go(page-1);else if(e.key==='ArrowRight'||e.key==='PageDown')go(page+1);else if(e.key==='Home')go(1);else if(e.key==='End')go(sheets.length);else if(e.key==='+'||e.key==='=')zoomAt(1.2);else if(e.key==='-')zoomAt(1/1.2);else if(e.key.toLowerCase()==='r')setRotation(rotation+90);else if(e.key.toLowerCase()==='w')fit('width');else if(e.key.toLowerCase()==='f')fit('page');else if(e.key==='Escape')closeSidebar();},{capture:true});
document.addEventListener('gesturestart',e=>e.preventDefault(),{passive:false});document.addEventListener('gesturechange',e=>e.preventDefault(),{passive:false});
let rt;window.addEventListener('resize',()=>{clearTimeout(rt);rt=setTimeout(()=>{if(mode==='page'||mode==='width')fit(mode);},160);});window.addEventListener('orientationchange',()=>setTimeout(()=>fit('page'),250));
loadProject();
